[package]
name = "pipeawesome2"
version = "0.1.0"
authors = ["Matthew Forrester <matthew.forrester@speechmarks.com>"]
edition = "2018"

[dependencies]
futures = "0.3.16"

[dependencies.async-std]
version = "1.9.0"
features = ["unstable"]
